# Generated by Django 3.2.3 on 2021-06-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicio'),
        ),
    ]
